spring:
  application:
    name: LinkShort
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener
    username: root
    password: ${DB_PASSWORD:sujal}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      connect-timeout: 2000

server:
  port: 8080